PATCH  http://localhost:3001/user/695168a9051d05fa90e8f55b
Content-Type: application/json

{
  "userName":"",
  "email":"mirseyed23@gmail.com",
  "password":""
}
#  GET http://localhost:3001/directory